/* ═══════════════════════════════════════════════════════════
   AURA · library — where tracks come from.

   Three sources, all optional:
     1. audio/manifest.json  (generated by tools/build-manifest.mjs)
     2. files the user drops in / picks  (stay on device, in IndexedDB)
     3. a folder handle, on browsers with the File System Access API

   Includes a small ID3v2 reader and an .lrc parser — no libraries.
   ═══════════════════════════════════════════════════════════ */
import { uid, readBuffer, readText } from './util.js';
import { blobs } from './db.js';

export const AUDIO_RE = /\.(mp3|m4a|aac|ogg|oga|opus|wav|flac|webm)$/i;

/* ── track shape ──────────────────────────────────────────── */
export function makeTrack(partial = {}) {
  return {
    id: partial.id || uid('t_'),
    title: partial.title || 'Unknown title',
    artist: partial.artist || 'Unknown artist',
    album: partial.album || '',
    genre: partial.genre || [],
    year: partial.year || null,
    src: partial.src || '',
    cover: partial.cover || '',
    duration: partial.duration || 0,
    addedAt: partial.addedAt || Date.now(),
    local: !!partial.local,
    blobKey: partial.blobKey || null,
    lrc: partial.lrc || null,
    ...partial,
  };
}

/* ── 1 · manifest ─────────────────────────────────────────── */
export async function loadManifest(url = 'audio/manifest.json') {
  try {
    const res = await fetch(url, { cache: 'no-cache' });
    if (!res.ok) return [];
    const json = await res.json();
    const list = Array.isArray(json) ? json : (json.tracks || []);
    return list.map((raw, i) => makeTrack({
      id: raw.id || `m_${i}_${(raw.src || raw.audio || '').replace(/\W+/g, '').slice(-16)}`,
      title: raw.title,
      artist: raw.artist,
      album: raw.album,
      genre: [].concat(raw.genre || []).filter(Boolean),
      year: raw.year,
      src: raw.src || raw.audio,
      cover: raw.cover || raw.art || '',
      duration: raw.duration || 0,
      lrc: raw.lrc || null,
      addedAt: raw.addedAt || Date.now() - (list.length - i) * 1000,
    })).filter(t => t.src);
  } catch (err) {
    console.warn('[aura] no manifest at', url, '—', err.message);
    return [];
  }
}

/** drop tracks whose files 404, so the library never shows dead rows */
export async function pruneMissing(tracks, onProgress) {
  const alive = [];
  let done = 0;
  await Promise.all(tracks.map(async (t) => {
    if (t.local || t.src.startsWith('blob:') || t.src.startsWith('data:')) { alive.push(t); return bump(); }
    try {
      const res = await fetch(t.src, { method: 'HEAD' });
      if (res.ok) alive.push(t);
      else console.info('[aura] skipping missing file:', t.src);
    } catch { alive.push(t); }   // network hiccup — keep it, the player will report on play
    bump();
  }));
  function bump() { onProgress?.(++done, tracks.length); }
  return alive.sort((a, b) => tracks.indexOf(a) - tracks.indexOf(b));
}

/* ── 2 · local files ──────────────────────────────────────── */
export async function importFiles(fileList, { onProgress } = {}) {
  const files = [...fileList];
  const audioFiles = files.filter(f => AUDIO_RE.test(f.name) || f.type.startsWith('audio/'));
  const lrcFiles = files.filter(f => /\.lrc$/i.test(f.name));

  // pair .lrc files with their audio by basename
  const lrcMap = new Map();
  for (const f of lrcFiles) {
    try { lrcMap.set(baseName(f.name), await readText(f)); } catch {}
  }

  const out = [];
  for (let i = 0; i < audioFiles.length; i++) {
    const file = audioFiles[i];
    onProgress?.(i + 1, audioFiles.length, file.name);
    try {
      const key = `blob_${uid('')}`;
      await blobs.put(key, file);
      const tags = await readTags(file).catch(() => ({}));
      out.push(makeTrack({
        title: tags.title || prettyName(file.name),
        artist: tags.artist || 'Local file',
        album: tags.album || '',
        genre: tags.genre ? [tags.genre] : [],
        year: tags.year || null,
        cover: tags.cover || '',
        src: URL.createObjectURL(file),
        local: true,
        blobKey: key,
        lrc: lrcMap.get(baseName(file.name)) || tags.lyrics || null,
      }));
    } catch (err) {
      console.warn('[aura] could not import', file.name, err);
    }
  }
  return out;
}

/** re-attach object URLs for locally imported tracks after a reload */
export async function rehydrateLocal(tracks) {
  const live = [];
  for (const t of tracks) {
    if (!t.local || !t.blobKey) { live.push(t); continue; }
    const blob = await blobs.get(t.blobKey);
    if (!blob) continue;                       // the blob is gone — drop the row
    t.src = URL.createObjectURL(blob);
    live.push(t);
  }
  return live;
}

/* ── 3 · folder picker (Chromium) ─────────────────────────── */
export async function pickFolder() {
  if (!('showDirectoryPicker' in window)) throw new Error('unsupported');
  const dir = await window.showDirectoryPicker({ id: 'aura-audio', mode: 'read' });
  const files = [];
  await walk(dir, files, 0);
  return files;
}
async function walk(dir, out, depth) {
  if (depth > 4) return;
  for await (const entry of dir.values()) {
    if (entry.kind === 'file') {
      if (AUDIO_RE.test(entry.name) || /\.lrc$/i.test(entry.name)) out.push(await entry.getFile());
    } else if (entry.kind === 'directory') {
      await walk(entry, out, depth + 1);
    }
  }
}

const baseName = (n) => n.replace(/\.[^.]+$/, '').toLowerCase();
const prettyName = (n) => n.replace(/\.[^.]+$/, '').replace(/[_-]+/g, ' ').replace(/^\d+\s*[.\-]\s*/, '').trim();

/* ═══════════════════════════════════════════════════════════
   ID3v2 reader — enough of the spec to fill the library well
   ═══════════════════════════════════════════════════════════ */
export async function readTags(file) {
  const head = await readBuffer(file.slice(0, 10));
  const h = new Uint8Array(head);
  if (h[0] !== 0x49 || h[1] !== 0x44 || h[2] !== 0x33) return {};   // no "ID3"

  const major = h[3];
  const size = synchsafe(h[6], h[7], h[8], h[9]);
  const buf = new Uint8Array(await readBuffer(file.slice(10, 10 + size)));

  const out = {};
  const idLen = major === 2 ? 3 : 4;
  let p = 0;

  while (p + idLen + (major === 2 ? 3 : 6) <= buf.length) {
    const id = str(buf, p, idLen);
    if (!/^[A-Z0-9]{3,4}$/.test(id)) break;            // padding reached
    p += idLen;

    let frameSize;
    if (major === 2) { frameSize = (buf[p] << 16) | (buf[p + 1] << 8) | buf[p + 2]; p += 3; }
    else if (major === 4) { frameSize = synchsafe(buf[p], buf[p + 1], buf[p + 2], buf[p + 3]); p += 4; p += 2; }
    else { frameSize = (buf[p] << 24) | (buf[p + 1] << 16) | (buf[p + 2] << 8) | buf[p + 3]; p += 4; p += 2; }

    if (frameSize <= 0 || p + frameSize > buf.length) break;
    const body = buf.subarray(p, p + frameSize);
    p += frameSize;

    switch (id) {
      case 'TIT2': case 'TT2': out.title  = decodeText(body); break;
      case 'TPE1': case 'TP1': out.artist = decodeText(body); break;
      case 'TALB': case 'TAL': out.album  = decodeText(body); break;
      case 'TCON': case 'TCO': out.genre  = cleanGenre(decodeText(body)); break;
      case 'TRCK': case 'TRK': out.track  = parseInt(decodeText(body), 10) || null; break;
      case 'TYER': case 'TYE': case 'TDRC':
        out.year = parseInt(String(decodeText(body)).slice(0, 4), 10) || null; break;
      case 'USLT': case 'ULT': out.lyrics = decodeLyrics(body); break;
      case 'APIC': case 'PIC': {
        const pic = decodePicture(body, major);
        if (pic && !out.cover) out.cover = pic;
        break;
      }
    }
  }
  return out;
}

const synchsafe = (a, b, c, d) => (a << 21) | (b << 14) | (c << 7) | d;
const str = (buf, at, len) => String.fromCharCode(...buf.subarray(at, at + len));

function decodeText(body) {
  if (!body.length) return '';
  const enc = body[0];
  const data = body.subarray(1);
  return decodeBy(enc, data).replace(/\0+$/, '').trim();
}

function decodeBy(enc, data) {
  try {
    if (enc === 0) return new TextDecoder('iso-8859-1').decode(data);
    if (enc === 1) {
      // UTF-16 with BOM
      if (data[0] === 0xFF && data[1] === 0xFE) return new TextDecoder('utf-16le').decode(data.subarray(2));
      if (data[0] === 0xFE && data[1] === 0xFF) return new TextDecoder('utf-16be').decode(data.subarray(2));
      return new TextDecoder('utf-16le').decode(data);
    }
    if (enc === 2) return new TextDecoder('utf-16be').decode(data);
    return new TextDecoder('utf-8').decode(data);
  } catch { return ''; }
}

function decodeLyrics(body) {
  if (body.length < 5) return null;
  const enc = body[0];
  let at = 4;                                   // skip encoding + 3-byte language
  // skip the content descriptor, terminated by 1 or 2 nulls depending on encoding
  const wide = enc === 1 || enc === 2;
  while (at < body.length) {
    if (wide) { if (body[at] === 0 && body[at + 1] === 0) { at += 2; break; } at += 2; }
    else { if (body[at] === 0) { at += 1; break; } at += 1; }
  }
  const text = decodeBy(enc, body.subarray(at)).replace(/\0/g, '').trim();
  return text || null;
}

function decodePicture(body, major) {
  try {
    let at = 1;
    let mime;
    if (major === 2) { mime = 'image/' + str(body, 1, 3).toLowerCase().replace('jpg', 'jpeg'); at = 4; }
    else {
      let end = at;
      while (end < body.length && body[end] !== 0) end++;
      mime = str(body, at, end - at) || 'image/jpeg';
      at = end + 1;
    }
    at += 1;                                     // picture type
    // description, null-terminated (assume single-byte; wide descriptions are rare here)
    while (at < body.length && body[at] !== 0) at++;
    at += 1;
    const bytes = body.subarray(at);
    if (bytes.length < 64) return null;
    return URL.createObjectURL(new Blob([bytes], { type: mime }));
  } catch { return null; }
}

const ID3_GENRES = ['Blues','Classic Rock','Country','Dance','Disco','Funk','Grunge','Hip-Hop','Jazz','Metal','New Age','Oldies','Other','Pop','R&B','Rap','Reggae','Rock','Techno','Industrial','Alternative','Ska','Death Metal','Pranks','Soundtrack','Euro-Techno','Ambient','Trip-Hop','Vocal','Jazz+Funk','Fusion','Trance','Classical','Instrumental','Acid','House','Game','Sound Clip','Gospel','Noise','Alt. Rock','Bass','Soul','Punk','Space','Meditative','Instrumental Pop','Instrumental Rock','Ethnic','Gothic','Darkwave','Techno-Industrial','Electronic','Pop-Folk','Eurodance','Dream','Southern Rock','Comedy','Cult','Gangsta Rap','Top 40','Christian Rap','Pop/Funk','Jungle','Native American','Cabaret','New Wave','Psychedelic','Rave','Showtunes','Trailer','Lo-Fi','Tribal','Acid Punk','Acid Jazz','Polka','Retro','Musical','Rock & Roll','Hard Rock'];
function cleanGenre(raw) {
  if (!raw) return '';
  const m = raw.match(/^\((\d+)\)/);
  if (m) return ID3_GENRES[+m[1]] || raw.replace(/^\(\d+\)/, '').trim();
  if (/^\d+$/.test(raw)) return ID3_GENRES[+raw] || raw;
  return raw;
}

/* ═══════════════════════════════════════════════════════════
   .lrc parser → [{ t: seconds, text }]
   ═══════════════════════════════════════════════════════════ */
export function parseLRC(text) {
  if (!text) return null;
  const lines = String(text).split(/\r?\n/);
  const out = [];
  let offset = 0;

  for (const line of lines) {
    const off = line.match(/^\s*\[offset:\s*([+-]?\d+)\s*\]/i);
    if (off) { offset = parseInt(off[1], 10) / 1000; continue; }

    const stamps = [...line.matchAll(/\[(\d{1,3}):(\d{1,2})(?:[.:](\d{1,3}))?\]/g)];
    if (!stamps.length) continue;
    const body = line.replace(/\[[^\]]*\]/g, '').trim();
    for (const s of stamps) {
      const frac = s[3] ? parseInt(s[3].padEnd(3, '0'), 10) / 1000 : 0;
      out.push({ t: (+s[1]) * 60 + (+s[2]) + frac + offset, text: body });
    }
  }
  if (!out.length) {
    // plain (unsynced) lyrics — still worth showing
    const plain = lines.map(l => l.trim()).filter(Boolean);
    return plain.length ? plain.map(text => ({ t: -1, text })) : null;
  }
  return out.sort((a, b) => a.t - b.t);
}

/* Sidecar lyrics are convenient but most libraries have none, and a blind
   probe per track fills the console with 404s. Try a handful; if every one
   misses, assume this library has no .lrc files and stop asking. */
let lrcMisses = 0;
const LRC_GIVE_UP_AFTER = 4;

/** find a .lrc sitting next to the audio file */
export async function fetchLRC(track) {
  if (track.lrc) {
    if (typeof track.lrc !== 'string') return null;
    // a manifest entry may point at the file rather than inline the text
    if (!/\n/.test(track.lrc) && /\.lrc$/i.test(track.lrc)) {
      try {
        const res = await fetch(track.lrc);
        return res.ok ? await res.text() : null;
      } catch { return null; }
    }
    return track.lrc;
  }
  if (track.local || !track.src || /^(blob|data):/.test(track.src)) return null;
  if (lrcMisses >= LRC_GIVE_UP_AFTER) return null;

  try {
    const res = await fetch(track.src.replace(/\.[^.]+$/, '.lrc'));
    if (res.ok) { lrcMisses = 0; return res.text(); }
  } catch {}
  lrcMisses++;
  return null;
}

/* ── grouping helpers for the Library view ────────────────── */
export function groupBy(tracks, key) {
  const map = new Map();
  for (const t of tracks) {
    const vals = key === 'genre' ? (t.genre?.length ? t.genre : ['Unsorted']) : [t[key] || 'Unknown'];
    for (const v of vals) {
      if (!map.has(v)) map.set(v, []);
      map.get(v).push(t);
    }
  }
  return [...map.entries()].sort((a, b) => b[1].length - a[1].length);
}

export const SORTS = {
  added:  (a, b) => b.addedAt - a.addedAt,
  title:  (a, b) => a.title.localeCompare(b.title),
  artist: (a, b) => a.artist.localeCompare(b.artist) || a.title.localeCompare(b.title),
  album:  (a, b) => (a.album || '~').localeCompare(b.album || '~') || a.title.localeCompare(b.title),
  longest:(a, b) => (b.duration || 0) - (a.duration || 0),
};
