#!/usr/bin/env node
/* ═══════════════════════════════════════════════════════════
   Reads images/chars/palettes.json and writes css/chars.css —
   a full light + dark token set per character, built from the
   colours actually present in their artwork.

   Add a character: drop <id>-src.png in images/chars/, add a
   row to CHARACTERS below, then
     node tools/prep-art.mjs && node tools/gen-themes.mjs
   ═══════════════════════════════════════════════════════════ */
import { readFileSync, writeFileSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');

export const CHARACTERS = [
  { id: 'aoi',   name: 'Aoi',   tag: 'ribbon blue',  blurb: 'cool, composed, summer afternoon' },
  { id: 'nyx',   name: 'Nyx',   tag: 'midnight cat', blurb: 'lamplight and late hours' },
  { id: 'mizu',  name: 'Mizu',  tag: 'shoreline',    blurb: 'salt air and open water' },
  { id: 'kaede', name: 'Kaede', tag: 'hot spring',   blurb: 'steam, neon dusk, mountain quiet' },
];

const pal = JSON.parse(readFileSync(resolve(ROOT, 'images/chars/palettes.json'), 'utf8'));

const hsl = (h, s, l, a) => `hsl(${h} ${s}% ${l}%${a != null ? ` / ${a}` : ''})`;

function block(c) {
  const p = pal[c.id];
  if (!p) throw new Error(`no palette for ${c.id} — run prep-art.mjs first`);
  const [a1, a2, a3] = p.accent;
  const [l1, l2, l3] = p.accentLight;
  // Tint the neutrals with the *accent* hue, not the image's average dark.
  // Aoi's darks average to the green foliage behind her, which would put a
  // green-grey UI under a blue theme.
  const H = p.hue[0];
  const S = Math.round(Math.min(p.dark.s * 100, 30));

  return `
/* ── ${c.name} · ${c.tag} ─────────────────────────────── */
[data-theme="${c.id}"][data-mode="dark"]{
  --bg-0:${hsl(H, S, 4)}; --bg-1:${hsl(H, S, 7)}; --bg-2:${hsl(H, S, 11)};
  --bg-grad:radial-gradient(130% 100% at 78% 0%, ${hsl(H, S + 6, 13)} 0%, ${hsl(H, S, 7)} 46%, ${hsl(H, S, 3)} 100%);
  --surface:${hsl(H, S - 4, 12)}; --surface-2:${hsl(H, S - 4, 16)};
  --stroke:${hsl(H, S, 30, '.42')}; --stroke-2:${hsl(H, S, 38)};
  --accent:${a1}; --accent-2:${a2}; --accent-3:${a3};
  --accent-grad:linear-gradient(120deg, ${a1}, ${a2} 45%, ${a3});
  --glow:color-mix(in oklab, ${a1} 62%, transparent);
}
[data-theme="${c.id}"][data-mode="light"]{
  --bg-0:${hsl(H, 26, 97)}; --bg-1:${hsl(H, 28, 94)}; --bg-2:${hsl(H, 26, 90)};
  --bg-grad:radial-gradient(130% 100% at 78% 0%, ${hsl(H, 34, 93)} 0%, ${hsl(H, 26, 97)} 52%, ${hsl(H, 22, 96)} 100%);
  --surface:${hsl(H, 30, 100)}; --surface-2:${hsl(H, 30, 96)};
  --stroke:${hsl(H, 24, 85)}; --stroke-2:${hsl(H, 22, 74)};
  --accent:${l1}; --accent-2:${l2}; --accent-3:${l3};
  --accent-grad:linear-gradient(120deg, ${l1}, ${l2} 45%, ${l3});
  --glow:color-mix(in oklab, ${l1} 38%, transparent);
}`;
}

const css = `/* ═══════════════════════════════════════════════════════════
   GENERATED by tools/gen-themes.mjs — do not edit by hand.
   Every value below is derived from the artwork in
   images/chars/ via tools/prep-art.mjs.
   ═══════════════════════════════════════════════════════════ */
${CHARACTERS.map(block).join('\n')}

/* ── Null · no artwork, no distractions ─────────────────── */
[data-theme="mono"][data-mode="dark"]{
  --bg-0:#08080a; --bg-1:#0e0e11; --bg-2:#151519;
  --bg-grad:radial-gradient(130% 100% at 50% 0%,#1a1a1f 0%,#0d0d10 52%,#070708 100%);
  --surface:#15151a; --surface-2:#1c1c22;
  --stroke:#2a2a3270; --stroke-2:#3c3c47;
  --accent:#e8e8ef; --accent-2:#ffffff; --accent-3:#9a9aab;
  --accent-grad:linear-gradient(120deg,#e8e8ef,#ffffff 45%,#9a9aab);
  --glow:#ffffff55; --aurora-op:.2;
}
[data-theme="mono"][data-mode="light"]{
  --bg-0:#fbfbfc; --bg-1:#f3f3f5; --bg-2:#eaeaee;
  --bg-grad:radial-gradient(130% 100% at 50% 0%,#eeeef1 0%,#fafafb 55%,#f5f5f7 100%);
  --surface:#ffffff; --surface-2:#f5f5f8;
  --stroke:#e0e0e6; --stroke-2:#c6c6d0;
  --accent:#2a2a33; --accent-2:#4b4b58; --accent-3:#7a7a8a;
  --accent-grad:linear-gradient(120deg,#2a2a33,#4b4b58 45%,#7a7a8a);
  --glow:#2a2a3340; --aurora-op:.16;
}

/* the live accent-from-cover-art override still wins over all of it */
[data-artcolor="on"]{
  --accent:var(--art-accent,var(--accent));
  --accent-2:var(--art-accent-2,var(--accent-2));
  --accent-3:var(--art-accent-3,var(--accent-3));
  --accent-grad:linear-gradient(120deg,var(--accent),var(--accent-2) 45%,var(--accent-3));
  --glow:color-mix(in oklab,var(--accent) 62%,transparent);
}
`;

writeFileSync(resolve(ROOT, 'css/chars.css'), css);

// a small registry the app imports, so names live in one place
const registry = `/* GENERATED by tools/gen-themes.mjs — do not edit by hand. */
export const CHARACTERS = ${JSON.stringify(
  CHARACTERS.map(c => ({ ...c, palette: pal[c.id].accent, lqip: pal[c.id].lqip, size: pal[c.id].size })), null, 2)};
`;
writeFileSync(resolve(ROOT, 'js/characters.js'), registry);

console.log(`  ✓ css/chars.css      ${CHARACTERS.length} characters + mono, light and dark`);
console.log(`  ✓ js/characters.js   registry with palettes and placeholders`);
